import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij"]

[cursor]
style = "Block"

[font]
size = 16.0

[font.normal]
family = "Iosevka Nerd Font"

[font.bold]
family = "Iosevka Nerd Font"

[font.italic]
family = "Iosevka Nerd Font"

[window]
startup_mode = "Maximized"
dynamic_padding = true
opacity = 1
padding.x = 5
padding.y = 5
decorations = "Buttonless"
