import = ["~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]

shell = "/opt/homebrew/Cellar/tmux/3.4_1/bin/tmux"

[cursor]
style = "Block"

[font]
size = 16.0

[font.normal]
family = "Iosevka Nerd Font"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.95
padding.x = 5
padding.y = 5
decorations = "Buttonless"
